# Travis configuration for go
#
# See README for more information about this repository.
#
# This repository does NOT do any deployments or installs.  However,
# it includes a lot of integration tests, which often require
# credentials.
#Z
#  * decrypt service account credentials
#  * install the Google Cloud SDK command line tools (gcloud)
#  * cache the gcloud installation and setup
#  * test and build the go code
#
language: go

before_install:
# Coverage tools
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge

# NB: Encrypted values are not defined in forks or pull requests.
# Decrypt the tar archive containing the GCP service account key files.
#
# After unpacking, there should be one service account key file for every GCP
# project referenced in the "deploy" section. These keys authenticate the
# gcloud deploy operations.

#- travis/decrypt.sh "$encrypted_361547783275_key" "$encrypted_361547783275_iv"
#  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp
- echo Branch is ${TRAVIS_BRANCH} and Tag is $TRAVIS_TAG

# These directories will be cached on successful "script" builds, and restored,
# if available, to save time on future builds.
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script:
- go test -covermode=count -coverprofile=cloudtest.cov -v github.com/m-lab/go/cloudtest

# Coveralls
- $HOME/gopath/bin/gocovmerge cloudtest.cov > merge.cov
- $HOME/gopath/bin/goveralls -coverprofile=merge.cov -service=travis-ci
